export const ENV = {
  HOST_BACKEND: import.meta.env.PUBLIC_HOST_BACKEND,
  HOST_AIIDA: import.meta.env.PUBLIC_HOST_AIIDA,
  EXPLORE_URL: import.meta.env.PUBLIC_EXPLORE_URL,
  EXT_CORE_APP_DOMAIN: import.meta.env.PUBLIC_EXT_CORE_APP_DOMAIN,
  EXT_CONTRIB_APP_DOMAIN: import.meta.env.PUBLIC_EXT_CONTRIB_APP_DOMAIN,
  COMMON_REST_ENDPOINT: import.meta.env.PUBLIC_COMMON_REST_ENDPOINT,
};
